// AUTO-GENERATED BY scripts/sync-art.mjs
// DO NOT EDIT DIRECTLY. Edit src/data/art-source.json instead.

export interface ArtItem {
  id: string;
  title: string;
  creator: string;
  cover: string;
  type: "music" | "book" | "movie";
  extra?: string;
}

export const artData: ArtItem[] = [
  {
    "id": "book-1",
    "title": "白夜行",
    "creator": "东野圭吾",
    "type": "book",
    "extra": "绝望的深渊与无尽的守护",
    "cover": "/images/content/art/book_book-1.jpg"
  },
  {
    "id": "book-2",
    "title": "秘密",
    "creator": "东野圭吾",
    "type": "book",
    "extra": "命运交织下的情感纠葛",
    "cover": "/images/content/art/book_book-2.svg"
  },
  {
    "id": "book-3",
    "title": "嫌疑人X的献身",
    "creator": "东野圭吾",
    "type": "book",
    "extra": "纯粹的数学，纯粹的爱",
    "cover": "/images/content/art/book_book-3.svg"
  },
  {
    "id": "book-4",
    "title": "幻夜",
    "creator": "东野圭吾",
    "type": "book",
    "extra": "灵魂挣扎下的宿命悲歌",
    "cover": "/images/content/art/book_book-4.svg"
  },
  {
    "id": "book-5",
    "title": "恶意",
    "creator": "东野圭吾",
    "type": "book",
    "extra": "令人战栗的人性深渊",
    "cover": "/images/content/art/book_book-5.svg"
  },
  {
    "id": "book-6",
    "title": "催眠师手记",
    "creator": "高铭",
    "type": "book",
    "extra": "探索心灵深处的隐秘档案",
    "cover": "/images/content/art/book_book-6.jpg"
  },
  {
    "id": "book-7",
    "title": "猎魔人",
    "creator": "安德烈·斯帕克沃斯基",
    "type": "book",
    "extra": "命运之剑，奇幻史诗巨作",
    "cover": "/images/content/art/book_book-7.svg"
  },
  {
    "id": "music-1",
    "title": "The Dark Side of the Moon",
    "creator": "Pink Floyd",
    "type": "music",
    "extra": "Progressive Rock",
    "cover": "/images/content/art/music_music-1.jpg"
  },
  {
    "id": "music-2",
    "title": "Abbey Road",
    "creator": "The Beatles",
    "type": "music",
    "extra": "Classic Rock",
    "cover": "/images/content/art/music_music-2.jpg"
  },
  {
    "id": "music-3",
    "title": "Jay",
    "creator": "周杰伦",
    "type": "music",
    "extra": "Mandopop",
    "cover": "/images/content/art/music_music-3.jpg"
  },
  {
    "id": "music-4",
    "title": "Random Access Memories",
    "creator": "Daft Punk",
    "type": "music",
    "extra": "Electronic",
    "cover": "/images/content/art/music_music-4.jpg"
  },
  {
    "id": "music-5",
    "title": "Thriller",
    "creator": "Michael Jackson",
    "type": "music",
    "extra": "Pop",
    "cover": "/images/content/art/music_music-5.jpg"
  },
  {
    "id": "music-6",
    "title": "A Night at the Opera",
    "creator": "Queen",
    "type": "music",
    "extra": "Glam Rock",
    "cover": "/images/content/art/music_music-6.jpg"
  },
  {
    "id": "movie-1",
    "title": "肖申克的救赎",
    "creator": "弗兰克·德拉邦特",
    "type": "movie",
    "extra": "经典救赎神作",
    "cover": "/images/content/art/movie_movie-1.jpg"
  },
  {
    "id": "movie-2",
    "title": "霸王别姬",
    "creator": "陈凯歌",
    "type": "movie",
    "extra": "华语电影巅峰之作",
    "cover": "/images/content/art/movie_movie-2.jpg"
  },
  {
    "id": "movie-3",
    "title": "盗梦空间",
    "creator": "克里斯托弗·诺兰",
    "type": "movie",
    "extra": "烧脑科幻巨作",
    "cover": "/images/content/art/movie_movie-3.jpg"
  },
  {
    "id": "movie-4",
    "title": "千与千寻",
    "creator": "宫崎骏",
    "type": "movie",
    "extra": "治愈心灵的奇幻冒险",
    "cover": "/images/content/art/movie_movie-4.jpg"
  },
  {
    "id": "movie-5",
    "title": "星际穿越",
    "creator": "克里斯托弗·诺兰",
    "type": "movie",
    "extra": "爱与维度的时空科幻",
    "cover": "/images/content/art/movie_movie-5.jpg"
  },
  {
    "id": "movie-6",
    "title": "楚门的世界",
    "creator": "彼得·威尔",
    "type": "movie",
    "extra": "打破虚假现实的自由之作",
    "cover": "/images/content/art/movie_movie-6.jpg"
  }
];
